apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: network-home
  namespace: metallb-system
spec:
  addresses:
    - 10.0.8.1/24
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: network-home
  namespace: metallb-system
spec:
  ipAddressPools:
  - network-home

