apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1  # You can adjust this number to specify how many replicas you want.
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      dnsPolicy: Default
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]  # Command to run (e.g., sleep for 1 hour)

